/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardClassroomsIndexRouteImport } from './routes/dashboard/classrooms/index'
import { Route as DashboardClassroomsClassroomIdRouteRouteImport } from './routes/dashboard/classrooms/$classroomId/route'
import { Route as DashboardClassroomsListRouteImport } from './routes/dashboard/classrooms/list'
import { Route as DashboardClassroomsNewRouteImport } from './routes/dashboard/classrooms/new'
import { Route as DashboardClassroomsScheduleRouteImport } from './routes/dashboard/classrooms/schedule'
import { Route as DashboardClassroomsStudentsRouteImport } from './routes/dashboard/classrooms/students'
import { Route as DashboardClassroomsClassroomIdIndexRouteImport } from './routes/dashboard/classrooms/$classroomId/index'
import { Route as DashboardClassroomsClassroomIdPeopleRouteRouteImport } from './routes/dashboard/classrooms/$classroomId/people/route'
import { Route as DashboardClassroomsClassroomIdSessionsRouteRouteImport } from './routes/dashboard/classrooms/$classroomId/sessions/route'
import { Route as DashboardClassroomsClassroomIdPeopleIndexRouteImport } from './routes/dashboard/classrooms/$classroomId/people/index'
import { Route as DashboardClassroomsClassroomIdPeopleMemberIdRouteImport } from './routes/dashboard/classrooms/$classroomId/people/$memberId'
import { Route as DashboardClassroomsClassroomIdSessionsIndexRouteImport } from './routes/dashboard/classrooms/$classroomId/sessions/index'
import { Route as DashboardClassroomsClassroomIdSessionsSessionIdRouteImport } from './routes/dashboard/classrooms/$classroomId/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassroomsIndexRoute =
  DashboardClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdRouteRoute =
  DashboardClassroomsClassroomIdRouteRouteImport.update({
    id: '/classrooms/$classroomId',
    path: '/classrooms/$classroomId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsListRoute = DashboardClassroomsListRouteImport.update({
  id: '/classrooms/list',
  path: '/classrooms/list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassroomsNewRoute = DashboardClassroomsNewRouteImport.update({
  id: '/classrooms/new',
  path: '/classrooms/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassroomsScheduleRoute =
  DashboardClassroomsScheduleRouteImport.update({
    id: '/classrooms/schedule',
    path: '/classrooms/schedule',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsStudentsRoute =
  DashboardClassroomsStudentsRouteImport.update({
    id: '/classrooms/students',
    path: '/classrooms/students',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdIndexRoute =
  DashboardClassroomsClassroomIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardClassroomsClassroomIdRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdPeopleRouteRoute =
  DashboardClassroomsClassroomIdPeopleRouteRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => DashboardClassroomsClassroomIdRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdSessionsRouteRoute =
  DashboardClassroomsClassroomIdSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardClassroomsClassroomIdRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdPeopleIndexRoute =
  DashboardClassroomsClassroomIdPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardClassroomsClassroomIdPeopleRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdPeopleMemberIdRoute =
  DashboardClassroomsClassroomIdPeopleMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => DashboardClassroomsClassroomIdPeopleRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdSessionsIndexRoute =
  DashboardClassroomsClassroomIdSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardClassroomsClassroomIdSessionsRouteRoute,
  } as any)
const DashboardClassroomsClassroomIdSessionsSessionIdRoute =
  DashboardClassroomsClassroomIdSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => DashboardClassroomsClassroomIdSessionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classrooms/$classroomId': typeof DashboardClassroomsClassroomIdRouteRouteWithChildren
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms/': typeof DashboardClassroomsIndexRoute
  '/dashboard/classrooms/$classroomId/people': typeof DashboardClassroomsClassroomIdPeopleRouteRouteWithChildren
  '/dashboard/classrooms/$classroomId/sessions': typeof DashboardClassroomsClassroomIdSessionsRouteRouteWithChildren
  '/dashboard/classrooms/$classroomId/': typeof DashboardClassroomsClassroomIdIndexRoute
  '/dashboard/classrooms/$classroomId/people/$memberId': typeof DashboardClassroomsClassroomIdPeopleMemberIdRoute
  '/dashboard/classrooms/$classroomId/sessions/$sessionId': typeof DashboardClassroomsClassroomIdSessionsSessionIdRoute
  '/dashboard/classrooms/$classroomId/people/': typeof DashboardClassroomsClassroomIdPeopleIndexRoute
  '/dashboard/classrooms/$classroomId/sessions/': typeof DashboardClassroomsClassroomIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms': typeof DashboardClassroomsIndexRoute
  '/dashboard/classrooms/$classroomId': typeof DashboardClassroomsClassroomIdIndexRoute
  '/dashboard/classrooms/$classroomId/people/$memberId': typeof DashboardClassroomsClassroomIdPeopleMemberIdRoute
  '/dashboard/classrooms/$classroomId/sessions/$sessionId': typeof DashboardClassroomsClassroomIdSessionsSessionIdRoute
  '/dashboard/classrooms/$classroomId/people': typeof DashboardClassroomsClassroomIdPeopleIndexRoute
  '/dashboard/classrooms/$classroomId/sessions': typeof DashboardClassroomsClassroomIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classrooms/$classroomId': typeof DashboardClassroomsClassroomIdRouteRouteWithChildren
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms/': typeof DashboardClassroomsIndexRoute
  '/dashboard/classrooms/$classroomId/people': typeof DashboardClassroomsClassroomIdPeopleRouteRouteWithChildren
  '/dashboard/classrooms/$classroomId/sessions': typeof DashboardClassroomsClassroomIdSessionsRouteRouteWithChildren
  '/dashboard/classrooms/$classroomId/': typeof DashboardClassroomsClassroomIdIndexRoute
  '/dashboard/classrooms/$classroomId/people/$memberId': typeof DashboardClassroomsClassroomIdPeopleMemberIdRoute
  '/dashboard/classrooms/$classroomId/sessions/$sessionId': typeof DashboardClassroomsClassroomIdSessionsSessionIdRoute
  '/dashboard/classrooms/$classroomId/people/': typeof DashboardClassroomsClassroomIdPeopleIndexRoute
  '/dashboard/classrooms/$classroomId/sessions/': typeof DashboardClassroomsClassroomIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/callback'
    | '/onboarding'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/classrooms/$classroomId'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/new'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms/'
    | '/dashboard/classrooms/$classroomId/people'
    | '/dashboard/classrooms/$classroomId/sessions'
    | '/dashboard/classrooms/$classroomId/'
    | '/dashboard/classrooms/$classroomId/people/$memberId'
    | '/dashboard/classrooms/$classroomId/sessions/$sessionId'
    | '/dashboard/classrooms/$classroomId/people/'
    | '/dashboard/classrooms/$classroomId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/onboarding'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/new'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms'
    | '/dashboard/classrooms/$classroomId'
    | '/dashboard/classrooms/$classroomId/people/$memberId'
    | '/dashboard/classrooms/$classroomId/sessions/$sessionId'
    | '/dashboard/classrooms/$classroomId/people'
    | '/dashboard/classrooms/$classroomId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/callback'
    | '/onboarding'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/classrooms/$classroomId'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/new'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms/'
    | '/dashboard/classrooms/$classroomId/people'
    | '/dashboard/classrooms/$classroomId/sessions'
    | '/dashboard/classrooms/$classroomId/'
    | '/dashboard/classrooms/$classroomId/people/$memberId'
    | '/dashboard/classrooms/$classroomId/sessions/$sessionId'
    | '/dashboard/classrooms/$classroomId/people/'
    | '/dashboard/classrooms/$classroomId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/': {
      id: '/dashboard/classrooms/'
      path: '/classrooms'
      fullPath: '/dashboard/classrooms/'
      preLoaderRoute: typeof DashboardClassroomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/$classroomId': {
      id: '/dashboard/classrooms/$classroomId'
      path: '/classrooms/$classroomId'
      fullPath: '/dashboard/classrooms/$classroomId'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/list': {
      id: '/dashboard/classrooms/list'
      path: '/classrooms/list'
      fullPath: '/dashboard/classrooms/list'
      preLoaderRoute: typeof DashboardClassroomsListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/new': {
      id: '/dashboard/classrooms/new'
      path: '/classrooms/new'
      fullPath: '/dashboard/classrooms/new'
      preLoaderRoute: typeof DashboardClassroomsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/schedule': {
      id: '/dashboard/classrooms/schedule'
      path: '/classrooms/schedule'
      fullPath: '/dashboard/classrooms/schedule'
      preLoaderRoute: typeof DashboardClassroomsScheduleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/students': {
      id: '/dashboard/classrooms/students'
      path: '/classrooms/students'
      fullPath: '/dashboard/classrooms/students'
      preLoaderRoute: typeof DashboardClassroomsStudentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/$classroomId/': {
      id: '/dashboard/classrooms/$classroomId/'
      path: '/'
      fullPath: '/dashboard/classrooms/$classroomId/'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdRouteRoute
    }
    '/dashboard/classrooms/$classroomId/people': {
      id: '/dashboard/classrooms/$classroomId/people'
      path: '/people'
      fullPath: '/dashboard/classrooms/$classroomId/people'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdPeopleRouteRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdRouteRoute
    }
    '/dashboard/classrooms/$classroomId/sessions': {
      id: '/dashboard/classrooms/$classroomId/sessions'
      path: '/sessions'
      fullPath: '/dashboard/classrooms/$classroomId/sessions'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdSessionsRouteRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdRouteRoute
    }
    '/dashboard/classrooms/$classroomId/people/': {
      id: '/dashboard/classrooms/$classroomId/people/'
      path: '/'
      fullPath: '/dashboard/classrooms/$classroomId/people/'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdPeopleIndexRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdPeopleRouteRoute
    }
    '/dashboard/classrooms/$classroomId/people/$memberId': {
      id: '/dashboard/classrooms/$classroomId/people/$memberId'
      path: '/$memberId'
      fullPath: '/dashboard/classrooms/$classroomId/people/$memberId'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdPeopleMemberIdRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdPeopleRouteRoute
    }
    '/dashboard/classrooms/$classroomId/sessions/': {
      id: '/dashboard/classrooms/$classroomId/sessions/'
      path: '/'
      fullPath: '/dashboard/classrooms/$classroomId/sessions/'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdSessionsIndexRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdSessionsRouteRoute
    }
    '/dashboard/classrooms/$classroomId/sessions/$sessionId': {
      id: '/dashboard/classrooms/$classroomId/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/dashboard/classrooms/$classroomId/sessions/$sessionId'
      preLoaderRoute: typeof DashboardClassroomsClassroomIdSessionsSessionIdRouteImport
      parentRoute: typeof DashboardClassroomsClassroomIdSessionsRouteRoute
    }
  }
}

interface DashboardClassroomsClassroomIdPeopleRouteRouteChildren {
  DashboardClassroomsClassroomIdPeopleMemberIdRoute: typeof DashboardClassroomsClassroomIdPeopleMemberIdRoute
  DashboardClassroomsClassroomIdPeopleIndexRoute: typeof DashboardClassroomsClassroomIdPeopleIndexRoute
}

const DashboardClassroomsClassroomIdPeopleRouteRouteChildren: DashboardClassroomsClassroomIdPeopleRouteRouteChildren =
  {
    DashboardClassroomsClassroomIdPeopleMemberIdRoute:
      DashboardClassroomsClassroomIdPeopleMemberIdRoute,
    DashboardClassroomsClassroomIdPeopleIndexRoute:
      DashboardClassroomsClassroomIdPeopleIndexRoute,
  }

const DashboardClassroomsClassroomIdPeopleRouteRouteWithChildren =
  DashboardClassroomsClassroomIdPeopleRouteRoute._addFileChildren(
    DashboardClassroomsClassroomIdPeopleRouteRouteChildren,
  )

interface DashboardClassroomsClassroomIdSessionsRouteRouteChildren {
  DashboardClassroomsClassroomIdSessionsSessionIdRoute: typeof DashboardClassroomsClassroomIdSessionsSessionIdRoute
  DashboardClassroomsClassroomIdSessionsIndexRoute: typeof DashboardClassroomsClassroomIdSessionsIndexRoute
}

const DashboardClassroomsClassroomIdSessionsRouteRouteChildren: DashboardClassroomsClassroomIdSessionsRouteRouteChildren =
  {
    DashboardClassroomsClassroomIdSessionsSessionIdRoute:
      DashboardClassroomsClassroomIdSessionsSessionIdRoute,
    DashboardClassroomsClassroomIdSessionsIndexRoute:
      DashboardClassroomsClassroomIdSessionsIndexRoute,
  }

const DashboardClassroomsClassroomIdSessionsRouteRouteWithChildren =
  DashboardClassroomsClassroomIdSessionsRouteRoute._addFileChildren(
    DashboardClassroomsClassroomIdSessionsRouteRouteChildren,
  )

interface DashboardClassroomsClassroomIdRouteRouteChildren {
  DashboardClassroomsClassroomIdPeopleRouteRoute: typeof DashboardClassroomsClassroomIdPeopleRouteRouteWithChildren
  DashboardClassroomsClassroomIdSessionsRouteRoute: typeof DashboardClassroomsClassroomIdSessionsRouteRouteWithChildren
  DashboardClassroomsClassroomIdIndexRoute: typeof DashboardClassroomsClassroomIdIndexRoute
}

const DashboardClassroomsClassroomIdRouteRouteChildren: DashboardClassroomsClassroomIdRouteRouteChildren =
  {
    DashboardClassroomsClassroomIdPeopleRouteRoute:
      DashboardClassroomsClassroomIdPeopleRouteRouteWithChildren,
    DashboardClassroomsClassroomIdSessionsRouteRoute:
      DashboardClassroomsClassroomIdSessionsRouteRouteWithChildren,
    DashboardClassroomsClassroomIdIndexRoute:
      DashboardClassroomsClassroomIdIndexRoute,
  }

const DashboardClassroomsClassroomIdRouteRouteWithChildren =
  DashboardClassroomsClassroomIdRouteRoute._addFileChildren(
    DashboardClassroomsClassroomIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClassroomsClassroomIdRouteRoute: typeof DashboardClassroomsClassroomIdRouteRouteWithChildren
  DashboardClassroomsListRoute: typeof DashboardClassroomsListRoute
  DashboardClassroomsNewRoute: typeof DashboardClassroomsNewRoute
  DashboardClassroomsScheduleRoute: typeof DashboardClassroomsScheduleRoute
  DashboardClassroomsStudentsRoute: typeof DashboardClassroomsStudentsRoute
  DashboardClassroomsIndexRoute: typeof DashboardClassroomsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClassroomsClassroomIdRouteRoute:
    DashboardClassroomsClassroomIdRouteRouteWithChildren,
  DashboardClassroomsListRoute: DashboardClassroomsListRoute,
  DashboardClassroomsNewRoute: DashboardClassroomsNewRoute,
  DashboardClassroomsScheduleRoute: DashboardClassroomsScheduleRoute,
  DashboardClassroomsStudentsRoute: DashboardClassroomsStudentsRoute,
  DashboardClassroomsIndexRoute: DashboardClassroomsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
