/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardClassroomsIndexRouteImport } from './routes/dashboard/classrooms/index'
import { Route as DashboardClassroomsListRouteImport } from './routes/dashboard/classrooms/list'
import { Route as DashboardClassroomsScheduleRouteImport } from './routes/dashboard/classrooms/schedule'
import { Route as DashboardClassroomsStudentsRouteImport } from './routes/dashboard/classrooms/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassroomsIndexRoute =
  DashboardClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsListRoute = DashboardClassroomsListRouteImport.update({
  id: '/classrooms/list',
  path: '/classrooms/list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassroomsScheduleRoute =
  DashboardClassroomsScheduleRouteImport.update({
    id: '/classrooms/schedule',
    path: '/classrooms/schedule',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClassroomsStudentsRoute =
  DashboardClassroomsStudentsRouteImport.update({
    id: '/classrooms/students',
    path: '/classrooms/students',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms/': typeof DashboardClassroomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms': typeof DashboardClassroomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classrooms/list': typeof DashboardClassroomsListRoute
  '/dashboard/classrooms/schedule': typeof DashboardClassroomsScheduleRoute
  '/dashboard/classrooms/students': typeof DashboardClassroomsStudentsRoute
  '/dashboard/classrooms/': typeof DashboardClassroomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/callback'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/callback'
    | '/dashboard/courses'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/classrooms/list'
    | '/dashboard/classrooms/schedule'
    | '/dashboard/classrooms/students'
    | '/dashboard/classrooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/': {
      id: '/dashboard/classrooms/'
      path: '/classrooms'
      fullPath: '/dashboard/classrooms/'
      preLoaderRoute: typeof DashboardClassroomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/list': {
      id: '/dashboard/classrooms/list'
      path: '/classrooms/list'
      fullPath: '/dashboard/classrooms/list'
      preLoaderRoute: typeof DashboardClassroomsListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/schedule': {
      id: '/dashboard/classrooms/schedule'
      path: '/classrooms/schedule'
      fullPath: '/dashboard/classrooms/schedule'
      preLoaderRoute: typeof DashboardClassroomsScheduleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classrooms/students': {
      id: '/dashboard/classrooms/students'
      path: '/classrooms/students'
      fullPath: '/dashboard/classrooms/students'
      preLoaderRoute: typeof DashboardClassroomsStudentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClassroomsListRoute: typeof DashboardClassroomsListRoute
  DashboardClassroomsScheduleRoute: typeof DashboardClassroomsScheduleRoute
  DashboardClassroomsStudentsRoute: typeof DashboardClassroomsStudentsRoute
  DashboardClassroomsIndexRoute: typeof DashboardClassroomsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClassroomsListRoute: DashboardClassroomsListRoute,
  DashboardClassroomsScheduleRoute: DashboardClassroomsScheduleRoute,
  DashboardClassroomsStudentsRoute: DashboardClassroomsStudentsRoute,
  DashboardClassroomsIndexRoute: DashboardClassroomsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
